name: Update Trophies
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to allow pushing changes to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 for the latest version
      - name: Update Trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: akhil2099
      - name: Commit changes
        run: |
          git config --global user.name 'README-bot'
          git config --global user.email 'readme-bot@users.noreply.github.com'
          git add .
          git commit -m "Update GitHub Trophies" || exit 0
          git push
